# Extracción, limpieza y transformación de datos.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob

Se utiliza la librería glob para acceder a la carpeta especificada y listar las rutas de todos los archivos con extensión .xlsx.

In [2]:
lista_de_archivos = glob.glob(r'C:\Users\HP\Desktop\Trabajos para prender\Guayerd AI\Tienda Aurelion\Archivos excel/*xlsx')

In [3]:
lista_de_archivos

['C:\\Users\\HP\\Desktop\\Trabajos para prender\\Guayerd AI\\Tienda Aurelion\\Archivos excel\\Clientes.xlsx',
 'C:\\Users\\HP\\Desktop\\Trabajos para prender\\Guayerd AI\\Tienda Aurelion\\Archivos excel\\Detalle_ventas.xlsx',
 'C:\\Users\\HP\\Desktop\\Trabajos para prender\\Guayerd AI\\Tienda Aurelion\\Archivos excel\\Productos.xlsx',
 'C:\\Users\\HP\\Desktop\\Trabajos para prender\\Guayerd AI\\Tienda Aurelion\\Archivos excel\\Ventas.xlsx']

Se importan los datos de cada uno de los archivos de Excel y se asignan a variables independientes para su posterior análisis.

In [4]:
cliente = pd.read_excel(lista_de_archivos[0])
detalle_ventas = pd.read_excel(lista_de_archivos[1])
productos = pd.read_excel(lista_de_archivos[2])
ventas = pd.read_excel(lista_de_archivos[3])

Realizamos copias de los dataframe

In [5]:
cliente_df  = cliente.copy()
detalle_ventas_df = detalle_ventas.copy()
productos_df = productos.copy()
ventas_df = ventas.copy()

Exploramos las primeras 5 filas de los archivos y mostramos su estructura general.

In [6]:
cliente_df.head()

,id_cliente,nombre_cliente,email,ciudad,fecha_alta
0,1,Mariana Lopez,mariana.lopez@mail.com,Carlos Paz,2023-01-01
1,2,Nicolas Rojas,nicolas.rojas@mail.com,Carlos Paz,2023-01-02
2,3,Hernan Martinez,hernan.martinez@mail.com,Rio Cuarto,2023-01-03
3,4,Uma Martinez,uma.martinez@mail.com,Carlos Paz,2023-01-04
4,5,Agustina Flores,agustina.flores@mail.com,Cordoba,2023-01-05

In [7]:
productos_df.head()

   id_producto     nombre_producto  categoria  precio_unitario
0            1      Coca Cola 1.5L  Alimentos             2347
1            2          Pepsi 1.5L   Limpieza             4973
2            3         Sprite 1.5L  Alimentos             4964
3            4  Fanta Naranja 1.5L   Limpieza             2033
4            5  Agua Mineral 500ml  Alimentos             4777

In [8]:
detalle_ventas_df.head()

,id_venta,id_producto,nombre_producto,cantidad,precio_unitario,importe
0,1,90,Toallas Húmedas x50,1,2902,2902
1,2,82,Aceitunas Negras 200g,5,2394,11970
2,2,39,Helado Vainilla 1L,5,469,2345
3,2,70,Fernet 750ml,2,4061,8122
4,2,22,Medialunas de Manteca,1,2069,2069

In [9]:
ventas_df.head()

,id_venta,fecha,id_cliente,nombre_cliente,email,medio_pago
0,1,2024-06-19,62,Guadalupe Romero,guadalupe.romero@mail.com,tarjeta
1,2,2024-03-17,49,Olivia Gomez,olivia.gomez@mail.com,qr
2,3,2024-01-13,20,Tomas Acosta,tomas.acosta@mail.com,tarjeta
3,4,2024-02-27,36,Martina Molina,martina.molina@mail.com,transferencia
4,5,2024-06-11,56,Bruno Diaz,bruno.diaz@mail.com,tarjeta

Verificamos cuantas filas y columnas tienen los DataFrame

In [10]:
tablas1  = [cliente_df, ventas_df, detalle_ventas_df, productos_df]
tablas1_nombre = ['cliente_df', 'ventas_df', 'detalle_ventas_df', 'productos_df']
for i in range(len(tablas1)):
    print(f"filas y coluntas tiene tabla {tablas1_nombre[i]}: {tablas1[i].shape}")

filas y coluntas tiene tabla cliente_df: (100, 5)
filas y coluntas tiene tabla ventas_df: (120, 6)
filas y coluntas tiene tabla detalle_ventas_df: (343, 6)
filas y coluntas tiene tabla productos_df: (100, 4)

Comprobar si existen filas duplicadas para cada archivo.

In [11]:
for i in range(len(tablas1)):
    print(f"filas duplicadas en la tabla {tablas1_nombre[i]} : {tablas1[i].duplicated().sum()}")

filas duplicadas en la tabla cliente_df : 0
filas duplicadas en la tabla ventas_df : 0
filas duplicadas en la tabla detalle_ventas_df : 0
filas duplicadas en la tabla productos_df : 0

Contamos la cantidad de valores nulos de cada columna en cada DataFrame.

In [13]:
for i in range(len(tablas1)):
    print(f"Valores nulos de la tabla {tablas1_nombre[i]}: \n \n {tablas1[i].isnull().sum().reset_index().rename(columns = {'index': 'columnas', 0 : 'valores nulos'})}")
    print("""
    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------
    """)

Valores nulos de la tabla cliente_df:

          columnas  valores nulos
0      id_cliente              0
1  nombre_cliente              0
2           email              0
3          ciudad              0
4      fecha_alta              0

    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------

Valores nulos de la tabla ventas_df:

          columnas  valores nulos
0        id_venta              0
1           fecha              0
2      id_cliente              0
3  nombre_cliente              0
4           email              0
5      medio_pago              0

    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------

Valores nulos de la tabla detalle_ventas_df:

           columnas  valores nulos
0         id_venta              0
1      id_producto              0
2  nombre_producto              0
3         cantidad              0
4  precio_unitario              0
5          importe              0

    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------

Valores nulos de la tabla productos_df:

           columnas  valores nulos
0      id_producto              0
1  nombre_producto              0
2        categoria              0
3  precio_unitario              0

    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------

Identificar el tipo de dato correspondiente a cada columna en cada archivo.

In [16]:
for i in range(len(tablas1)):
    print("""
    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------
          """)
    print(f"Información de la tabla {tablas1_nombre[i]}")
    print('')
    print(tablas1[i].info())

    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------

Información de la tabla cliente_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      100 non-null    int64
 1   nombre_cliente  100 non-null    object
 2   email           100 non-null    object
 3   ciudad          100 non-null    object
 4   fecha_alta      100 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 4.0+ KB
None

    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------

Información de la tabla ventas_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venta        120 non-null    int64
 1   fecha           120 non-null    datetime64[ns]
 2   id_cliente      120 non-null    int64
 3   nombre_cliente  120 non-null    object
 4   email           120 non-null    object
 5   medio_pago      120 non-null    object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 5.8+ KB
None

    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------

Información de la tabla detalle_ventas_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 343 entries, 0 to 342
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         343 non-null    int64
 1   id_producto      343 non-null    int64
 2   nombre_producto  343 non-null    object
 3   cantidad         343 non-null    int64
 4   precio_unitario  343 non-null    int64
 5   importe          343 non-null    int64
dtypes: int64(5), object(1)
memory usage: 16.2+ KB
None

    -----------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------

Información de la tabla productos_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_producto      100 non-null    int64
 1   nombre_producto  100 non-null    object
 2   categoria        100 non-null    object
 3   precio_unitario  100 non-null    int64
dtypes: int64(2), object(2)
memory usage: 3.3+ KB
None

Buscamos si hay datos tipo float en las columnas precio unitario e importe. Así poder transformar las columnas al tipo de dato float.

In [17]:
Buscamos_datos_tipo_float_en_precios = [x for x in productos_df['precio_unitario'].unique().tolist() if isinstance(x, float)]
print(Buscamos_datos_tipo_float_en_precios)

[]

In [18]:
Buscamos_datos_tipo_float_en_precio_unitario_DV = [x for x in detalle_ventas_df['precio_unitario'].unique().tolist() if isinstance(x, float)]
print(Buscamos_datos_tipo_float_en_precio_unitario_DV)

[]

In [19]:
Buscamos_datos_tipo_float_en_importe = [x for x in detalle_ventas_df['importe'].unique().tolist() if isinstance(x, float)]
print(Buscamos_datos_tipo_float_en_importe)

[]

Por lo tanto, no hay datos tipo float en las columnas 'precio_unitario' y 'importe'.

Exportando los datos limpios a archivos excel.

In [ ]:
# cliente_df.to_excel('limpio_clientes.xlsx', index=False)
# detalle_ventas_df.to_excel('limpio_detalle_ventas.xlsx', index=False)
# productos_df.to_excel('limpio_productos.xlsx', index=False)
# ventas_df.to_excel('limpio_ventas.xlsx', index=False)